# Generated by Django 5.0.2 on 2024-02-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('bookname', models.CharField(max_length=30)),
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('edition', models.IntegerField()),
                ('shelfno', models.CharField(max_length=10)),
            ],
        ),
    ]
